### ISSUE TITLE
Backport to Python 2.7?

### ISSUE THREAD

**Issue by ahawker** [ahawker/ulid#1]
Here are some initial thoughts but definitely incomplete list of changes necessary.

* Switch hard coded `bytes` to be configurable to `str`.
* Loss of `int.to_bytes()` and `int.from_bytes()`.
* Loss of `datetime.timestamp()`
* Differences between `memoryview` and `buffer`?

**Comment by blakev** [comment]
I'm almost done with this, ~20 more errors to squash in the test suite, mostly with handling `bytes` vs `bytearray` in python2

**Comment by nicktimko** [comment]
@blakev what are you using to strip out all the function annotations; something automated or just discarding them all?

**Comment by blakev** [comment]
I did it by hand because there weren't too many.

This was the recommended way:

```python
def decode(value):
    ...
    ...
decode.__annotations__ = {'value': str, 'return': bytes_}
```

**Comment by ahawker** [comment]
Isn't there a backport of `typing` to 2.7? Or am I mis-remembering?

**Comment by blakev** [comment]
It doesn't really work like you'd expect. The two recommended formats are the `func.__annotations__` style or doing a single comment before the docstring:

```python
    @classmethod
    def from_bytes(cls, b, byteorder='big'):
        # type: (bytes, str) -> Int
       """ My function method turns these bytes to a number! """
```

PyCharm and other tools will pick up on these.

**Comment by ahawker** [comment]
Closing as py27 is being EOL'd very soon.
