### ISSUE TITLE
Datetime objects are naive

### ISSUE THREAD

**Issue by beevor** [ahawker/ulid#463]
`ulid.timestamp().datetime` returns a naive datetime object (lacking time zone information), but yet the time is in UTC. 

A naive datetime is ambiguous. Can the datetime be made aware by explicitly attaching the UTC time zone? The `datetime `module documentation has reasons why it is preferred to use aware datetimes to represent times in UTC

**Comment by ahawker** [comment]
#465 should address this issue by making them aware and in UTC. I will update and close this issue once the next version is deployed and available for use.

**Comment by ahawker** [comment]
This change should be available in version `0.2.0`
