### ISSUE TITLE
No module named 'ulid.api'

### ISSUE THREAD

**Issue by Reskov** [ahawker/ulid#479]
Starting ulid 0.2.0 I get this error when I try to simple install library

```
(venv) ➜  pip install ulid-py==1.0.0               
Collecting ulid-py==1.0.0
  Using cached https://files.pythonhosted.org/packages/3f/9e/deba154963e4eb00cd31b60f35329359dcbf8ad34a01371c10f32faf3867/ulid_py-1.0.0-py2.py3-none-any.whl
Installing collected packages: ulid-py
  Found existing installation: ulid-py 0.1.0
    Uninstalling ulid-py-0.1.0:
      Successfully uninstalled ulid-py-0.1.0
Successfully installed ulid-py-1.0.0
(venv) ➜  python3 <<< "import ulid" 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.8/site-packages/ulid/__init__.py", line 10, in <module>
    from .api import default, microsecond, monotonic
ModuleNotFoundError: No module named 'ulid.api'
```

Also, when I download a package from PyPI and unpack it there is not API folder inside

**Comment by ahawker** [comment]
Yikes. 👀  into it now...

**Comment by ahawker** [comment]
Version [1.1.0](https://pypi.org/project/ulid-py/1.1.0/) is available in pypi now and have yanked `1.0.0`.

Keeping this issue open (for now) for visibility. Please let me know if this latest package version is working properly for you.

**Comment by Reskov** [comment]
@ahawker yes, everything is good now! thanks

**Comment by ahawker** [comment]
@Reskov Excellent. My apologies for the issue and thanks for reporting the issue and confirming the fix!
