### ISSUE TITLE
How to derive a ULID from a string?

### ISSUE THREAD

**Issue by jamesshapiro** [ahawker/ulid#483]
Suppose you have

`ulid_string = '01EYV88PB2Y212QSR0AJ2JX5T4'`

How would you derive a ulid object from the string?

**Comment by jamesshapiro** [comment]
Nvmd, figured it out:

`parsed_ulid = ulid.parse(ulid_string)`

**Comment by ahawker** [comment]
`ulid.from_str` will be slightly more performant as `parse` attempts to handle all supported types/formats.
